#ifndef BGR444_H
#define BGR444_H

#define AliceBlue 0xFFE
#define AntiqueWhite 0xDEF
#define Aqua 0xFF0
#define Aquamarine 0xCF7
#define Azure 0xFFE
#define Beige 0xDEE
#define Bisque 0xCDF
#define Black 0x000
#define BlanchedAlmond 0xCEF
#define Blue 0xF00
#define BlueViolet 0xD38
#define Brown 0x22A
#define BurlyWood 0x8BD
#define CadetBlue 0x996
#define Chartreuse 0x0F7
#define Chocolate 0x26C
#define Coral 0x57F
#define CornflowerBlue 0xE96
#define Cornsilk 0xDFF
#define Crimson 0x41D
#define Cyan 0xFF0
#define DarkBlue 0x800
#define DarkCyan 0x880
#define DarkGoldenRod 0x18B
#define DarkGray 0xAAA
#define DarkGreen 0x060
#define DarkKhaki 0x6BB
#define DarkMagenta 0x808
#define DarkOliveGreen 0x365
#define DarkOrange 0x08F
#define DarkOrchid 0xC39
#define DarkRed 0x008
#define DarkSalmon 0x79E
#define DarkSeaGreen 0x8B8
#define DarkSlateBlue 0x844
#define DarkSlateGray 0x553
#define DarkTurquoise 0xCC0
#define DarkViolet 0xC09
#define DeepPink 0x91F
#define DeepSkyBlue 0xFB0
#define DimGray 0x666
#define DodgerBlue 0xF82
#define FireBrick 0x22A
#define FloralWhite 0xEFF
#define ForestGreen 0x282
#define Fuchsia 0xF0F
#define Gainsboro 0xDDD
#define GhostWhite 0xFFF
#define Gold 0x0DF
#define GoldenRod 0x2AD
#define Gray 0x888
#define Green 0x080
#define GreenYellow 0x3FA
#define HoneyDew 0xEFE
#define HotPink 0xB6F
#define IndianRed 0x55C
#define Indigo 0x804
#define Ivory 0xEFF
#define Khaki 0x8EE
#define Lavender 0xFEE
#define LavenderBlush 0xEEF
#define LawnGreen 0x0F7
#define LemonChiffon 0xCFF
#define LightBlue 0xEDA
#define LightCoral 0x88E
#define LightCyan 0xFFD
#define LightGoldenRodYellow 0xCFF
#define LightGray 0xCCC
#define LightGreen 0x8E8
#define LightPink 0xBBF
#define LightSalmon 0x79F
#define LightSeaGreen 0xAA2
#define LightSkyBlue 0xFC8
#define LightSlateGray 0x987
#define LightSteelBlue 0xDCA
#define LightYellow 0xDFF
#define Lime 0x0F0
#define LimeGreen 0x3C3
#define Linen 0xEEF
#define Magenta 0xF0F
#define Maroon 0x008
#define MediumAquaMarine 0xAC6
#define MediumBlue 0xC00
#define MediumOrchid 0xC5B
#define MediumPurple 0xD79
#define MediumSeaGreen 0x7B4
#define MediumSlateBlue 0xE67
#define MediumSpringGreen 0x9F0
#define MediumTurquoise 0xCC4
#define MediumVioletRed 0x81C
#define MidnightBlue 0x711
#define MintCream 0xFFE
#define MistyRose 0xDDF
#define Moccasin 0xBDF
#define NavajoWhite 0xADF
#define Navy 0x800
#define OldLace 0xEEF
#define Olive 0x088
#define OliveDrab 0x286
#define Orange 0x0AF
#define OrangeRed 0x04F
#define Orchid 0xD7D
#define PaleGoldenRod 0xAEE
#define PaleGreen 0x9F9
#define PaleTurquoise 0xEEA
#define PaleVioletRed 0x97D
#define PapayaWhip 0xDEF
#define PeachPuff 0xBDF
#define Peru 0x48C
#define Pink 0xCBF
#define Plum 0xD9D
#define PowderBlue 0xEDA
#define Purple 0x808
#define Red 0x00F
#define RosyBrown 0x88B
#define RoyalBlue 0xD64
#define SaddleBrown 0x148
#define Salmon 0x78F
#define SandyBrown 0x6AE
#define SeaGreen 0x583
#define SeaShell 0xEEF
#define Sienna 0x359
#define Silver 0xBBB
#define SkyBlue 0xEC8
#define SlateBlue 0xC56
#define SlateGray 0x887
#define Snow 0xFFF
#define SpringGreen 0x7F0
#define SteelBlue 0xB84
#define Tan 0x8BC
#define Teal 0x880
#define Thistle 0xDBD
#define Tomato 0x46F
#define Turquoise 0xCD4
#define Violet 0xE8E
#define Wheat 0xBDE
#define White 0xFFF
#define WhiteSmoke 0xEEE
#define Yellow 0x0FF
#define YellowGreen 0x3C9

#endif /* BGR444_H */