#define AliceBlue 0xEFF
#define AntiqueWhite 0xFED
#define Aqua 0x0FF
#define Aquamarine 0x7FC
#define Azure 0xEFF
#define Beige 0xEED
#define Bisque 0xFDC
#define Black 0x000
#define BlanchedAlmond 0xFEC
#define Blue 0x00F
#define BlueViolet 0x83D
#define Brown 0xA22
#define BurlyWood 0xDB8
#define CadetBlue 0x699
#define Chartreuse 0x7F0
#define Chocolate 0xC62
#define Coral 0xF75
#define CornflowerBlue 0x69E
#define Cornsilk 0xFFD
#define Crimson 0xD14
#define Cyan 0x0FF
#define DarkBlue 0x008
#define DarkCyan 0x088
#define DarkGoldenRod 0xB81
#define DarkGray 0xAAA
#define DarkGreen 0x060
#define DarkKhaki 0xBB6
#define DarkMagenta 0x808
#define DarkOliveGreen 0x563
#define DarkOrange 0xF80
#define DarkOrchid 0x93C
#define DarkRed 0x800
#define DarkSalmon 0xE97
#define DarkSeaGreen 0x8B8
#define DarkSlateBlue 0x448
#define DarkSlateGray 0x355
#define DarkTurquoise 0x0CC
#define DarkViolet 0x90C
#define DeepPink 0xF19
#define DeepSkyBlue 0x0BF
#define DimGray 0x666
#define DodgerBlue 0x28F
#define FireBrick 0xA22
#define FloralWhite 0xFFE
#define ForestGreen 0x282
#define Fuchsia 0xF0F
#define Gainsboro 0xDDD
#define GhostWhite 0xFFF
#define Gold 0xFD0
#define GoldenRod 0xDA2
#define Gray 0x888
#define Green 0x080
#define GreenYellow 0xAF3
#define HoneyDew 0xEFE
#define HotPink 0xF6B
#define IndianRed 0xC55
#define Indigo 0x408
#define Ivory 0xFFE
#define Khaki 0xEE8
#define Lavender 0xEEF
#define LavenderBlush 0xFEE
#define LawnGreen 0x7F0
#define LemonChiffon 0xFFC
#define LightBlue 0xADE
#define LightCoral 0xE88
#define LightCyan 0xDFF
#define LightGoldenRodYellow 0xFFC
#define LightGray 0xCCC
#define LightGreen 0x8E8
#define LightPink 0xFBB
#define LightSalmon 0xF97
#define LightSeaGreen 0x2AA
#define LightSkyBlue 0x8CF
#define LightSlateGray 0x789
#define LightSteelBlue 0xACD
#define LightYellow 0xFFD
#define Lime 0x0F0
#define LimeGreen 0x3C3
#define Linen 0xFEE
#define Magenta 0xF0F
#define Maroon 0x800
#define MediumAquaMarine 0x6CA
#define MediumBlue 0x00C
#define MediumOrchid 0xB5C
#define MediumPurple 0x97D
#define MediumSeaGreen 0x4B7
#define MediumSlateBlue 0x76E
#define MediumSpringGreen 0x0F9
#define MediumTurquoise 0x4CC
#define MediumVioletRed 0xC18
#define MidnightBlue 0x117
#define MintCream 0xEFF
#define MistyRose 0xFDD
#define Moccasin 0xFDB
#define NavajoWhite 0xFDA
#define Navy 0x008
#define OldLace 0xFEE
#define Olive 0x880
#define OliveDrab 0x682
#define Orange 0xFA0
#define OrangeRed 0xF40
#define Orchid 0xD7D
#define PaleGoldenRod 0xEEA
#define PaleGreen 0x9F9
#define PaleTurquoise 0xAEE
#define PaleVioletRed 0xD79
#define PapayaWhip 0xFED
#define PeachPuff 0xFDB
#define Peru 0xC84
#define Pink 0xFBC
#define Plum 0xD9D
#define PowderBlue 0xADE
#define Purple 0x808
#define Red 0xF00
#define RosyBrown 0xB88
#define RoyalBlue 0x46D
#define SaddleBrown 0x841
#define Salmon 0xF87
#define SandyBrown 0xEA6
#define SeaGreen 0x385
#define SeaShell 0xFEE
#define Sienna 0x953
#define Silver 0xBBB
#define SkyBlue 0x8CE
#define SlateBlue 0x65C
#define SlateGray 0x788
#define Snow 0xFFF
#define SpringGreen 0x0F7
#define SteelBlue 0x48B
#define Tan 0xCB8
#define Teal 0x088
#define Thistle 0xDBD
#define Tomato 0xF64
#define Turquoise 0x4DC
#define Violet 0xE8E
#define Wheat 0xEDB
#define White 0xFFF
#define WhiteSmoke 0xEEE
#define Yellow 0xFF0
#define YellowGreen 0x9C3